### ISSUE TITLE
Running Vistarsier on HPC

### ISSUE THREAD

**Issue by hajerkr** [mh-cad/vistarsier#23]
Hello,

Not sure who to reach out about this question so I thought I'd open an issue. Is it possible to run Vistarsier on the HPC from cmd? So that would be a Linux environment. Any information about that would be greatly appreciated. Looking forward to hearing from you.

**Comment by plwp** [comment]
Hi,

The command line version (which supports Nifti input/output) can be built for Linux. There are also some third party tools that need to be installed.

The steps for a Linux build are in the Docker file here:
https://github.com/mh-cad/vistarsier/blob/master/Dockerfile

If your environment supports Docker you can pull the prebuilt container from dockerhub using ‘Docker pull plwp/VisTarsier’


Cheers,

Pat

**Comment by hajerkr** [comment]
Hi Pat,

thank you for the quick response. I pulled the image using singularity x docker. Is there any documentation on how to run the segmentation script using T1 and FLAIR images for a set of subjects? Many thanks.

**Comment by hajerkr** [comment]
Hi @plwp , just wondering if you could help me out with the above? The documentation seems to only include setting up the environment, but I am not sure how to run it from cmd. Thanks a lot.

**Comment by plwp** [comment]
Hi,

The docker image contains the command line release as described here:
https://github.com/mh-cad/vistarsier/releases/tag/v0.3-beta-cmd

So to run via docker you'd use:
`docker run -v [local_path]:[container_path] plwp/vistarsier [prior_nifti] [current_nifti] [output_prefix]`

for example if you have a current_flair.nii and prior_flair.nii in your /data directory you'd run:
`docker run -v /data:/data plwp/vistarsier /data/prior_flair.nii /data/current_flair.nii /data`

If you want to run over a set of images you'd need to write your own script to loop through the pairs.

Just for clarification the output will be a difference map rather than a segmentation, and the input only needs to be FLAIR images.

-Pat
